### ISSUE TITLE
Move methods from Climate Toolkit into Psychrometrics Toolkit

### ISSUE THREAD

**Issue by vbeardow** [BHoM/Psychrometrics_Toolkit#12]
#### Description:
Add the following methods from Climate toolkit into Psychrometrics, following discussion on https://github.com/BuroHappoldEngineering/Climate_Toolkit/issues/204

- [x] DensityWater
- [x] SpecificHeatCapacityWater
- [x] SaturatedVapourPressureWater

Either replace with code previously in climate toolkit or with respective Psychrolib methods. 

Ensure documentation and QA/QC is complete and up-to-date for the methods.

**Comment by tg359** [comment]
@EKAdebo - these links should help you

Here are the methods in Climate_Toolkit currently that could be moved over:
- [DensityWater](https://github.com/BuroHappoldEngineering/Climate_Toolkit/blob/7df1cc2e3db5dc2f7af3646123bc09b9daa2fd5a/Climate_Engine/Compute/DensityWater.cs)
- [SpecificHeatCapacityWater](https://github.com/BuroHappoldEngineering/Climate_Toolkit/blob/7df1cc2e3db5dc2f7af3646123bc09b9daa2fd5a/Climate_Engine/Compute/SpecificHeatCapacityWater.cs)
- [SaturatedVapourPressureWater](https://github.com/BuroHappoldEngineering/Climate_Toolkit/blob/7df1cc2e3db5dc2f7af3646123bc09b9daa2fd5a/Climate_Engine/Compute/SaturatedVapourPressureWater.cs)

Or, even better than that, you could use the Psychrolib nuget package we have access to in this repository to create new methods - [here is an example for calculating Enthalpy from HumidityRatio in this toolkit currently](https://github.com/BHoM/Psychrometrics_Toolkit/blob/develop/Psychrometrics_Engine/Compute/EnthalpyHumidityRatio.cs).

**Comment by FraserGreenroyd** [comment]
`[PreviousVersion("6.2", "BH.Engine.Climate.Compute.DensityWater(System.Double)")]`

Needed for all methods moved.
